### ISSUE TITLE
Undefined variable: response

### ISSUE THREAD

**Issue by Fossil01** [aharen/OMDbAPI#5]
```
  Undefined variable: response

  at vendor/aharen/omdbapi/src/OMDbAPI.php:157
    153|
    154|             $body = $response->getBody();
    155|             $data = $body->getContents();
    156|         } catch (RequestException $e) {
  > 157|             $code = $response->getStatusCode();
    158|             $message = $response->getReasonPhrase();
    159|             $data = $e->getRequest();
    160|         } catch (ClientException $e) {
    161|             $code = $response->getStatusCode();

      +2 vendor frames
  3   app/Console/Commands/UpdateMovieRatings.php:56
      aharen\OMDbAPI::fetch()
```

**Comment by aharen** [comment]
Hi. 

Is this code from your own implementation?

Update the `$response` after the `catch` to `$e`

```
} catch (RequestException $e) {
    $code = $e->getStatusCode();
    $message = $e->getReasonPhrase();
    $data = $e->getRequest();
} catch (ClientException $e) {
    $code = $e->getStatusCode();
```

**Comment by Fossil01** [comment]
No this is in the packages code `  at vendor/aharen/omdbapi/src/OMDbAPI.php:157`

I am at `"aharen/omdbapi": "^2.0"` which seems to be 1eb34e050f0c3234e15b80ef318b80122aeefaa9 according to my composer.lock

**Comment by aharen** [comment]
Oh i see. Looking at the commit history, this issue was addressed on bd053f46345849cf1b3b7c5dfa12ca35e45f94b2

Can you try deleting the folder `vendor/aharen/omdbapi` and running `composer install` again?

Also, did you run `composer update` after making the change to `composer.json` file?

**Comment by Fossil01** [comment]
Ah I got it it's held back by an old Guzzle constraint:

aharen/omdbapi      v2.0.8      requires  guzzlehttp/guzzle (^6.2)
fossil01/**REMOVED**  dev-master  requires  guzzlehttp/guzzle (^7.2)

**Comment by aharen** [comment]
Oh you're right! It's been ages since i've used this one. An update is needed for sure 😅

If you're able to fix it and send a pull request it's more than welcome 😄

**Comment by Fossil01** [comment]
Done. If you could tag a new version so composer works that would be great :-)

**Comment by aharen** [comment]
Thank you very much 😄 

New release and tagged `2.1`
